### ISSUE TITLE
Need to explicitly call out MTU size for each version of the protocol

### ISSUE THREAD

**Issue by justinjdickow** [smartdevicelink/protocol_spec#4]

**Comment by justinjdickow** [comment]
Current plan is:

Protocol version 2 is 1488, protocol version 3 will be 128k, and protocol version 4 will be negotiated.

**Comment by justinjdickow** [comment]
Actually 3 and 4 are 128k and 5 will be negotiated.

**Comment by jacobkeeler** [comment]
Document with the release of protocol spec version 5
